name: cashlens
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.7.0
  cloud_firestore: ^5.5.0
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  flutter_blurhash: ^0.8.2
  google_fonts: ^6.2.1
  flutter_animate: ^4.2.0
  fl_chart: ^0.66.0
  flutter_svg: ^2.0.7
  sms_autofill: ^2.3.0
  telephony: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
